export enum FileActionTypes {
  SET_FILES = 'SET_FILES',
  SET_CURRENT_DIR = 'SET_CURRENT_DIR',
  ADD_FILE = 'ADD_FILE',
  SET_POPUP_DISPLAY = 'SET_POPUP_DISPLAY',
  PUSH_TO_STACK = 'PUSH_TO_STACK',
  DELETE_FILE = 'DELETE_FILE',
  SET_VIEW = 'SET_VIEW',
}
