export enum UploadActionTypes {
  SHOW_UPLOADER = 'SHOW_UPLOADER',
  HIDE_UPLOADER = 'HIDE_UPLOADER',
  ADD_UPLOAD_FILE = 'ADD_UPLOAD_FILE',
  REMOVE_UPLOAD_FILE = 'REMOVE_UPLOAD_FILE',
  CHANGE_UPLOAD_FILE = 'CHANGE_UPLOAD_FILE',
}
